/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CnMt4zHChkC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/vercel/kv/components/ui/button"
import { CardContent, Card, CardTitle, CardHeader } from "@/vercel/kv/components/ui/card"
import { AvatarImage, AvatarFallback, Avatar } from "@/vercel/kv/components/ui/avatar"

export function comments() {
  return (
    <div className="grid grid-cols-[1fr_300px] gap-8 p-8">
      <div className="space-y-8">
        <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-medium">Visual Board</h2>
            <div className="flex items-center gap-2">
              <Button size="sm" variant="outline">
                <PlusIcon className="h-4 w-4" />
                Add New
              </Button>
              <Button size="sm" variant="outline">
                <FilterIcon className="h-4 w-4" />
                Filter
              </Button>
            </div>
          </div>
          <div className="mt-6 grid grid-cols-3 gap-4">
            <Card className="group relative h-40 cursor-pointer overflow-hidden rounded-lg bg-gray-100 transition-all hover:scale-105 dark:bg-gray-800">
              <CardContent className="flex h-full flex-col justify-end p-4">
                <div className="space-y-1">
                  <h3 className="text-sm font-medium text-gray-900 group-hover:underline dark:text-gray-50">
                    Design Concept
                  </h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Brainstorming ideas</p>
                </div>
              </CardContent>
              <img
                alt="Visual Board Item"
                className="absolute inset-0 h-full w-full object-cover"
                height={160}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/160",
                  objectFit: "cover",
                }}
                width={300}
              />
            </Card>
            <Card className="group relative h-40 cursor-pointer overflow-hidden rounded-lg bg-gray-100 transition-all hover:scale-105 dark:bg-gray-800">
              <CardContent className="flex h-full flex-col justify-end p-4">
                <div className="space-y-1">
                  <h3 className="text-sm font-medium text-gray-900 group-hover:underline dark:text-gray-50">
                    User Flow
                  </h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Mapping user interactions</p>
                </div>
              </CardContent>
              <img
                alt="Visual Board Item"
                className="absolute inset-0 h-full w-full object-cover"
                height={160}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/160",
                  objectFit: "cover",
                }}
                width={300}
              />
            </Card>
            <Card className="group relative h-40 cursor-pointer overflow-hidden rounded-lg bg-gray-100 transition-all hover:scale-105 dark:bg-gray-800">
              <CardContent className="flex h-full flex-col justify-end p-4">
                <div className="space-y-1">
                  <h3 className="text-sm font-medium text-gray-900 group-hover:underline dark:text-gray-50">
                    Wireframes
                  </h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Laying out the interface</p>
                </div>
              </CardContent>
              <img
                alt="Visual Board Item"
                className="absolute inset-0 h-full w-full object-cover"
                height={160}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/160",
                  objectFit: "cover",
                }}
                width={300}
              />
            </Card>
            <Card className="group relative h-40 cursor-pointer overflow-hidden rounded-lg bg-gray-100 transition-all hover:scale-105 dark:bg-gray-800">
              <CardContent className="flex h-full flex-col justify-end p-4">
                <div className="space-y-1">
                  <h3 className="text-sm font-medium text-gray-900 group-hover:underline dark:text-gray-50">
                    Prototypes
                  </h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Interactive demos</p>
                </div>
              </CardContent>
              <img
                alt="Visual Board Item"
                className="absolute inset-0 h-full w-full object-cover"
                height={160}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/160",
                  objectFit: "cover",
                }}
                width={300}
              />
            </Card>
            <Card className="group relative h-40 cursor-pointer overflow-hidden rounded-lg bg-gray-100 transition-all hover:scale-105 dark:bg-gray-800">
              <CardContent className="flex h-full flex-col justify-end p-4">
                <div className="space-y-1">
                  <h3 className="text-sm font-medium text-gray-900 group-hover:underline dark:text-gray-50">
                    UI Designs
                  </h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400">High-fidelity mockups</p>
                </div>
              </CardContent>
              <img
                alt="Visual Board Item"
                className="absolute inset-0 h-full w-full object-cover"
                height={160}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/160",
                  objectFit: "cover",
                }}
                width={300}
              />
            </Card>
            <Card className="group relative h-40 cursor-pointer overflow-hidden rounded-lg bg-gray-100 transition-all hover:scale-105 dark:bg-gray-800">
              <CardContent className="flex h-full flex-col justify-end p-4">
                <div className="space-y-1">
                  <h3 className="text-sm font-medium text-gray-900 group-hover:underline dark:text-gray-50">
                    Branding
                  </h3>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Logo and identity</p>
                </div>
              </CardContent>
              <img
                alt="Visual Board Item"
                className="absolute inset-0 h-full w-full object-cover"
                height={160}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/160",
                  objectFit: "cover",
                }}
                width={300}
              />
            </Card>
          </div>
        </div>
        <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-medium">Comments</h2>
            <Button size="sm" variant="outline">
              <PlusIcon className="h-4 w-4" />
              Add Comment
            </Button>
          </div>
          <div className="mt-6 space-y-6">
            <div className="flex items-start gap-4">
              <Avatar>
                <AvatarImage src="https://github.com/nextjs.png" />
                <AvatarFallback>NX</AvatarFallback>
              </Avatar>
              <div className="flex-1 space-y-2">
                <div className="flex items-center justify-between">
                  <h4 className="text-sm font-medium">Next.js</h4>
                  <p className="text-xs text-gray-500 dark:text-gray-400">2 days ago</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Great work on the visual board! I really like the clean and modern design. The prototypes look super
                  interactive too.
                </p>
                <div className="flex items-center gap-2">
                  <Button size="sm" variant="ghost">
                    <FacebookIcon className="h-4 w-4" />
                    Like
                  </Button>
                  <Button size="sm" variant="ghost">
                    <ReplyIcon className="h-4 w-4" />
                    Reply
                  </Button>
                </div>
              </div>
            </div>
            <div className="flex items-start gap-4">
              <Avatar>
                <AvatarImage src="https://github.com/vercel.png" />
                <AvatarFallback>VC</AvatarFallback>
              </Avatar>
              <div className="flex-1 space-y-2">
                <div className="flex items-center justify-between">
                  <h4 className="text-sm font-medium">Vercel</h4>
                  <p className="text-xs text-gray-500 dark:text-gray-400">3 days ago</p>
                </div>
                <p className="text-sm text-gray-500 dark:text-gray-400">
                  Awesome job on the branding and UI designs! The visual board looks really cohesive and on-brand.
                </p>
                <div className="flex items-center gap-2">
                  <Button size="sm" variant="ghost">
                    <FacebookIcon className="h-4 w-4" />
                    Like
                  </Button>
                  <Button size="sm" variant="ghost">
                    <ReplyIcon className="h-4 w-4" />
                    Reply
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="space-y-8">
        <Card>
          <CardHeader>
            <CardTitle>Sponsored</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="flex items-center gap-4">
                <img
                  alt="Sponsored Ad"
                  className="rounded-lg"
                  height={80}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "80/80",
                    objectFit: "cover",
                  }}
                  width={80}
                />
                <div className="space-y-1">
                  <h4 className="text-sm font-medium">Acme Design Tools</h4>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Boost your design workflow</p>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <img
                  alt="Sponsored Ad"
                  className="rounded-lg"
                  height={80}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "80/80",
                    objectFit: "cover",
                  }}
                  width={80}
                />
                <div className="space-y-1">
                  <h4 className="text-sm font-medium">Productivity App</h4>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Stay organized and on track</p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Promotions</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="flex items-center gap-4">
                <img
                  alt="Promotion"
                  className="rounded-lg"
                  height={80}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "80/80",
                    objectFit: "cover",
                  }}
                  width={80}
                />
                <div className="space-y-1">
                  <h4 className="text-sm font-medium">Design Bundle Sale</h4>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Save 50% on our design tools</p>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <img
                  alt="Promotion"
                  className="rounded-lg"
                  height={80}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "80/80",
                    objectFit: "cover",
                  }}
                  width={80}
                />
                <div className="space-y-1">
                  <h4 className="text-sm font-medium">Productivity Webinar</h4>
                  <p className="text-xs text-gray-500 dark:text-gray-400">Learn how to boost your workflow</p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function ReplyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="9 17 4 12 9 7" />
      <path d="M20 18v-2a4 4 0 0 0-4-4H4" />
    </svg>
  )
}
